### ISSUE TITLE
View analytics reports for subset of all pages (ability to filter).

### ISSUE THREAD

**Issue by rcalfredson** [IBM/page-lab#28]
Currently, analytics reports aggregate result from all pages. In addition to this existing functionality, users may want a way to specify a subset they would like to analyze.

There could be a variety of ways to specify the desired subset of pages. For example, perhaps users would like to filter down to URLs containing a given subset, or perhaps they would like to input a comma-separated list of URLs they know in advance.

It would be possible for the user to view the dashboard, the report-card tiles and the detailed page summaries using that filtered list.

**Comment by rcalfredson** [comment]
Thank you for the feedback! Have just seen the message, and think this makes sense! For a chance to meet, there is one meeting that Ann Marie Fred, Tim. Figgins, and I are planning to have today at 10:00 AM to talk about filter functionality at large. Do you think that time would be good for us to discuss also? I apologize for the short notice on that, and of course we could meet at a different time if it would work better

Before that time, I will begin to experiment with model-based approach, and hopefully would have something toward that goal to share by then. Thanks again.

**Comment by amfred** [comment]
Some of this is internal implementation details, but stepping back from a usability perspective, a simple substring match is the easiest for people to understand.
However, we have a business requirement coming up next (as in this week) to also be able to filter the results by business unit and geography, so keep that in mind, please.  

For example:
* Show me all Marketplace pages
* Show me all Marketplace pages in France
* Show me all pages owned by the Analytics business unit

**Comment by rcalfredson** [comment]
Would like please to share an initial "gist" or sketch of new models based on comment above. Are these similar to the approach you are thinking about?

```
class UrlFilter(models.Model):
    """
    A Url filter to apply.
    """
    key = models.CharField(max_length=255, choices=[('host_name', 'host_name'), ('pathname0', 'pathname0')])

    def getMatches(self):
        return [obj for obj in Url.objects.all() if getattr(obj, self.key) == self.match]

class UrlFilterRule(models.Model):
    """
    Specific instance of URL filter.
    """
    match = models.CharField(max_length=255, null=True)
    filter = models.ForeignKey(UrlFilter, on_delete=models.CASCADE)
    def getMatches(self):
        return [obj for obj in Url.objects.all() if getattr(obj, self.filter.key) == self.match]
```

Have added an initial one as a test, using some new properties of `Url`. My inference is that the changes to `Url` would take place on the DB level, rather than on the runtime level via derived properties; do you think this is accurate? Thank you.

**Comment by daviddahl** [comment]
Let me create a PR later today / tomorrow to illustrate. I think the filtering data should be persisted

**Comment by rcalfredson** [comment]
That sounds good, thank you! Would like please to confirm, it is correct that this would be replacement for, not a companion to, the current proposal? In other words, are there parts of the existing P.R.'s we would want to retain/use, or should they be closed instead?

**Comment by daviddahl** [comment]
I'll make the models and we can then meet to discuss

**Comment by daviddahl** [comment]
Thes screens should give you an idea on the concept I am working on
![selection_163](https://user-images.githubusercontent.com/23880/48164533-c3173680-e2b0-11e8-90cd-36fb51ccc693.png)
![selection_162](https://user-images.githubusercontent.com/23880/48164534-c3173680-e2b0-11e8-9b18-2fa9e8d00285.png)

**Comment by rcalfredson** [comment]
Yes, thank you, that sounds good! Have already been working with the code, and the approach is clear to me. Would you want to meet for it today? I have complete availability.

**Comment by daviddahl** [comment]
I wanted to mention that the service and UI of this new functionality should look like this:

a view is created to list all of the `UrlFilter` objects at `/url-filters/`

Each filter corresponds to a url and view that produces the dashboard at the UrlFilter's name: /url-filters/my-url-filter-for-such-and-such

we want to use slugs for the names and make them unique

In the UrlFilter view function we have a very simple operation:

```
myUrls = UrlFilter.objects.get(name='my-url-filter-name').run_query()

```

`myUrls` are then consumed by the dashboard generating - the dashboard generation code may need to be pulled into a helper function

**Comment by ecumike** [comment]
Closing. In `master` as of PR #46

**Comment by amfred** [comment]
Agreed, the filters are working.  Looking forward to the "AND" and "OR" functionality next!
