### ISSUE TITLE
Teach users that not all pages are monitored, and how to request that a new page be monitored

### ISSUE THREAD

**Issue by amfred** [IBM/page-lab#34]
We need to be able to see how different sets of pages are performing over time.  PageLab can scan and keep data on thousands of web pages, but it can't scan the entire Internet.  We need to have a simple way for end users to understand that some URLs are not monitored, and to learn how to request that new pages be monitored.  This user feedback will help each Page Lab owner monitor the most important web pages.

Acceptance Criteria:
1) Add documentation explaining how to request that a new page be added to the list of pages my Page Lab instance is monitoring.
2) If I search for a specific web page URL and it's not currently being monitored, or if any of my searches come back with no results, show a message explaining (briefly) that the page(s) is not being monitored, and explain how I can request that it be added.
3) Sanitize all data on input and HTML-escape the data on output, for security purposes.

**Comment by amfred** [comment]
So your recommendation is to extend an internal open source fork of the project to have information o how to request that new pages be monitored?  I can buy that.

I'll start a different thread for the internal version.

**Comment by daviddahl** [comment]
> So your recommendation is to extend an internal open source fork of the project to have information o how to request that new pages be monitored? I can buy that.

No. Not at *all*.

We are using this: https://docs.djangoproject.com/en/2.1/ref/contrib/flatpages/ to handle CMS-like pages inside the app.

Go ahead and provide us a page title, description and HTML content and we can add the page to the running instance

**Comment by amfred** [comment]
I'm closing the Github issue and we'll track the page creation with an internal RTC story, 109041.
It's a few stories down on the TODO list, not the highest priority.
