### ISSUE TITLE
 Change report page chart and data table data set timeframe 

### ISSUE THREAD

**Issue by ecumike** [IBM/page-lab#60]
- Update both chart and data table to only show latest three week period runs. 
- Move chart data and data table data into separate WSR view with date option.
- Update report ui to include links on each for 3 “weeks” and “full history”
  - onclick makes WSR, reloads chart/table
- Future function add in start/end data in wsr view. UI tbd.

**Comment by ecumike** [comment]
Handled in #61

**Comment by ecumike** [comment]
In master.

**Comment by daviddahl** [comment]
w00t
